server:
  port: 8003

spring:
  application:
    name: statistic-trade-data-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/message?authSource=admin
      authentication-database: admin
      auto-index-creation: true
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

